apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nuclear-penguin-nodejs 
  janus-idp.io/tekton: nuclear-penguin-nodejs
  backstage.io/kubernetes-id: nuclear-penguin-nodejs
  backstage.io/kubernetes-namespace: flavius-e2e 
  app.kubernetes.io/part-of: nuclear-penguin-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  