apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nuclear-penguin-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nuclear-penguin-nodejs 
  name: nuclear-penguin-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: nuclear-penguin-nodejs 
